name = "Revo"
grammar = "revo"
path_suffixes = ["rv", "revo"]
line_comments = ["# "]
tab_size = 2
first_line_pattern = '^#!.*\brevo\b'
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]
